### ISSUE TITLE
Fail compiling check_mesh

### ISSUE THREAD

**Issue by jwjeremy** [SeisSol/Meshing#46]
**Describe the bug**
I was compiling the check_mesh and encountered some errors during the make. The error is probably due to the PUML.h? The error is attached in the [make.log](https://github.com/SeisSol/Meshing/files/11278505/make.log) and and the cmake log file is also attached [cmake.log](https://github.com/SeisSol/Meshing/files/11278502/cmake.log).

Thank you! 

**Expected behavior**
Compile the chech_mesh

**Comment by davschneller** [comment]
Hi, that's due to an old submodule reference in PUML2. I've put up a PR to change that in PUML2 (https://github.com/TUM-I5/PUML2/pull/10 )—and there'll be another PR for this repository here soon.

EDIT: PR in PUML2 has been merged, and the PR for this module here is out, it's #47.

Until then, you should be able to fix the problem locally by going to `submodules/PUML/submodules/utils` and run `git checkout master` (maybe followed by a `git pull`, if the repository was initialized more than a year ago).
